### ISSUE TITLE
GitHub repository metadata points to non-TLS URL

### ISSUE THREAD

**Issue by JeremyRand** [linuxboot/heads#1263]
The repository metadata for https://github.com/osresearch/heads points to http://osresearch.net/ (without TLS).  Can the metadata be updated to use the HTTPS version?

**Comment by tlaurion** [comment]
@JeremyRand I tried to find where on several occasions since you opened the issue, but I can't either modify the about section myself or do not find any place where to do it as a collaborator?

**Comment by JeremyRand** [comment]
> @JeremyRand I tried to find where on several occasions since you opened the issue, but I can't either modify the about section myself or do not find any place where to do it as a collaborator?

@tlaurion I believe changing that metadata requires either Admin or Owner privs on the repo; collaborators can't do it.

**Comment by tlaurion** [comment]
@osresearch?
