### ISSUE TITLE
Upstreaming eDP/FHD to coreboot 4.22 if quick enough

### ISSUE THREAD

**Issue by tlaurion** [linuxboot/heads#1523]
Hey testers summarized under https://github.com/linuxboot/heads/issues/692 as: x230-fhd/edp variant: @n4ru @computer-user123 (nitro caster board) @Tonux599 @househead @pcm720 (eDP 4.0 board and 1440p display).

If I can come up with a PR for you to test, can one of you test it quick to see if it works as expected?

I would love to drop patches under Heads (to use coreboot 4.22 as is for FHD) and the window frame is short prior of 4.22 release.

Pushed today and had traction: https://review.coreboot.org/c/coreboot/+/28950/comments/ad637b80_49227412

That would be really appreciated, let me know today so I can do a PR just for that board to test.

**Comment by pcm720** [comment]
@tlaurion Sure, I don't mind testing the PR.

**Comment by tlaurion** [comment]
Alright, can't promise anything but will try to work on this when I have a coreboot commit to add.

**Comment by tlaurion** [comment]
Won't happen in time....
