### ISSUE TITLE
Set vm.panic_on_oom=1 in bootloader

### ISSUE THREAD

**Issue by DemiMarie** [linuxboot/heads#1619]
**Is your feature request related to a problem? Please describe.**
Shell scripts are not very good at handling unexpected errors.  The most likely cause of an unexpected error during boot is running out of memory, which should never happen.

**Describe the solution you'd like**
Panic the system if an unexpected out of memory happens during boot.

**Describe alternatives you've considered**
Fix all of the missing error checks.  I expect this to be difficult.

**Additional context**
Out-of-memory can cause any non-builtin command to fail without crashing the script, and shell scripts usually are not written to handle this.

**Comment by JonathonHall-Purism** [comment]
Agree 100%.  I'm planning to jump on a bunch of PB/Heads work in a few weeks, if nobody beats me to it I'll test it.

**Comment by tlaurion** [comment]
Understood that desired implementation here is to add `vm.panic_on_oom=1` in all coreboot config's kernel command line.
