### ISSUE TITLE
busybox build does not reproduce

### ISSUE THREAD

**Issue by JonathonHall-Purism** [linuxboot/heads#1636]
I compared a CI build of #1630 with my local build, the only remaining reproducibility issue is busybox.  All coreboot stages now reproduce, payload differs in the initrd only.

diffoscope identifies busybox.  There are a lot of differences in disassembly and relocations but I think they all stem from a difference in string data (which causes more layout differences, etc.):

```
│ │ │ ├── strings --all --bytes=8 {}
│ │ │ │ @@ -665,15 +665,16 @@
│ │ │ │  []A\A]A^A_
│ │ │ │  h[]A\A]A^A_
│ │ │ │  []A\A]A^A_
│ │ │ │  []A\A]A^A_
│ │ │ │  [A\A]A^A_]
│ │ │ │  AWAVAUATUH
│ │ │ │  []A\A]A^A_
│ │ │ │ -%Y-%m-%d %H:%M:%
│ │ │ │ +   @@@%Y-%m-%d %H:%M:%
│ │ │ │ +NO NAME    
│ │ │ │  JFS1BSFXI
│ │ │ │  hsqsreebb
│ │ │ │   multi-call binary.
│ │ │ │  No help available
│ │ │ │  section header
│ │ │ │  unknown user/group
│ │ │ │  keyword outside section
│ │ │ │ @@ -1969,15 +1970,14 @@
│ │ │ │  can't make FAT32 with >128 sectors/cluster
│ │ │ │  Device '%s':
│ │ │ │  heads:%u, sectors/track:%u, bytes/sector:%u
│ │ │ │  media descriptor:%02x
│ │ │ │  total sectors:%lu, clusters:%u, sectors/cluster:%u
│ │ │ │  FATs:2, sectors/FAT:%u
│ │ │ │  volumeID:%08x, label:'%s'
│ │ │ │ -NO NAME    
│ │ │ │  --More-- 
│ │ │ │  (%u%% of %lu bytes)
│ │ │ │  (Enter:next line Space:next page Q:quit R:show the rest)
│ │ │ │  mount('%s','%s','%s',0x%08lx,'%s'):%d
│ │ │ │  would do mount('%s','%s','%s',0x%08lx,'%s')
│ │ │ │  %s is write-protected, mounting read-only
│ │ │ │  unc=\\%s\%.*s,prefixpath=%s
```

Some date format string changed slightly, now starts with `   @@@`.  `NO NAME` also moved.

(left is CI, right is my local build, and I did a clean build by deleting build/x86 and install/x86 for this)

**Comment by tlaurion** [comment]
@JonathonHall-Purism some top of the head insight.

busybox module is actually the only one being rebuilt without caring of its .build status.

I wonder if this is not the root of the problem, coonsidering that CI rebuilds it multiple times depending of where that board is in the chain of workspace cache transfers.

I think a little rework on the busybox module to have this oldest module refreshed and respecting proper build recipes could probably resolve the problem altogether with a little bit of investigation.
