### ISSUE TITLE
Setting a TPM DUK on Ubuntu 24.04 fails at unpacking initramfs 

### ISSUE THREAD

**Issue by tlaurion** [linuxboot/heads#1644]
![PXL_20240420_023355792.jpg](https://github.com/linuxboot/heads/assets/827570/7c6a6a46-7efb-45b5-adf4-e3f83326508b)

Otherwise boots on x230 on master with DRK. 
So #1641 specific to nv41 @alex-nitrokey @daringer @nestire

**Comment by tlaurion** [comment]
@JonathonHall-Purism what on hell is `type 02214c18b266` will be subject to another PR down the path...

**Comment by JonathonHall-Purism** [comment]
It's LZ4.  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/decompress.c#n58

We'd need to ship an LZ4 decompressor (if we don't already), then add it to unpack_initramfs.sh: https://github.com/linuxboot/heads/blob/master/initrd/bin/unpack_initramfs.sh#L67.

**Comment by tlaurion** [comment]
Irrelevant under 24.10+ since they switched to zstd which was already supported. Added xz though, needed by debian derivatives (tested tails) on upcoming PR that will close this issue.
