### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by tlaurion** [linuxboot/heads#1718]
drafting at  https://www.perplexity.ai/search/can-you-draft-a-code-of-conduc-atHmG0fQRKCqzx7yoh2Lzg

**Comment by tlaurion** [comment]
@SergiiDmytruk I see you downvoted this issue, comments?

**Comment by tlaurion** [comment]
Code of conduct will vanish once I unbrick my nv41. Woukd appreciate review of collaborating.md still

**Comment by fhvyhjriur** [comment]
I also downvoted it. My explanation can be find here: https://github.com/linuxboot/heads/pull/1719#issuecomment-2244024191
