### ISSUE TITLE
Clean checkout  fails on first build of BOARD=r630

### ISSUE THREAD

**Issue by osresearch** [linuxboot/heads#360]
Looks like a failed dep for `PiSmmCore`.  Re-running make works.

**Comment by osresearch** [comment]
Looks like a problem in the linuxboot/edk2 Makefile, which doesn't specify PiSmmCore as an output from the edk2 build: https://github.com/linuxboot/edk2/blob/UDK2018/Makefile#L15

**Comment by mosayyebzadeh** [comment]
Re-running make does not work. Well, it finishes but the result image fails on the hardware complaining about missing DXE components.

**Comment by tlaurion** [comment]
@osresearch ?
