### ISSUE TITLE
flashtool documentation

### ISSUE THREAD

**Issue by tlaurion** [linuxboot/heads#388]
Is there any?

**Comment by osresearch** [comment]
I've just verified that `flashtool` works on my x230. Given a 7 MB ROM image:
```
flashtool -v -p 0xf8000000 -O 0x500000 -w /media/x230-5mb.rom
```

The `-p` is necessary to locate the PCIEXBAR: https://github.com/osresearch/flashtools/issues/1

It is very slow; the timeout delays while waiting for write to complete are likely too low.
