### ISSUE TITLE
distribution of an x230-flash image

### ISSUE THREAD

**Issue by merge** [linuxboot/heads#577]
I'm thinking about distributing a Heads `x230-flash` image as part of a [x230-skulls release](https://github.com/merge/skulls/releases) package. It's exactly the same procedure to flash as is a current Skulls image after all.

how sane is this thought? what do you think is legally necessary to include (without forking Heads :). Links to Heads sources only, with some build instructions?

Also, this would force us to stay reproducibly buildable at all times, which is good.

**Comment by tlaurion** [comment]
#734

**Comment by tlaurion** [comment]
#571

**Comment by tlaurion** [comment]
@merge I'm not against the idea!

**Comment by tlaurion** [comment]
@merge ping?
