### ISSUE TITLE
Cross compiler setup - C_INCLUDE_PATH etc

### ISSUE THREAD

**Issue by daym** [linuxboot/heads#609]
Hi,

we'd like to package Heads in the GNU Guix distribution.

There is a slight problem we are working around:

Our compilers use the (gcc) environment variables `CPATH`, `C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH`, `LIBRARY_PATH` (and `OBJC_INCLUDE_PATH` and `OBJCPLUS_INCLUDE_PATH`) in order to specify the location of the system headers, see `gcc/incpath.c`. Almost all our packages set those environment variables while building.

Heads builds its own cross compiler (via `musl-cross`) which we have already packaged.

However, when Heads later uses that cross compiler, it doesn't unset the environment variables above (it doesn't set them either--but they have been set by us before) and thus when using musl-cross's compiler we get a mix of cross and non-cross headers, which isn't good.

It would be nice if there was a generic mechanism to pass environment variables to a module. Right now, your `CROSS_TOOLS` `make` variable sometimes gets passed on as environment variable and sometimes only as (child) `make` variable--which isn't good.

Some of Heads' modules use the cross compiler and some use the native compiler, so it cannot be reliably automatically detected whether or not the environment variables are required--that is also why we don't just unset the environment variables before invoking `make` in Heads (with prebuilt `musl-cross`). For example the Heads module `linux` uses `elfutils` but there's no Heads module `elfutils` (neither cross-compiled using `musl-cross` nor otherwise). There are Heads modules that require both a cross and a non-cross (host) compiler.

Similar with `slsh` (which has a heads package) and `termcap` (which doesn't have a heads package - `ncurses` isn't used, right?).

Also, `libusb` seems to use `CXXCPP` which your main `Makefile` doesn't set up for the cross compiler (neither does it set up `CPP`).

**Comment by daym** [comment]
I suggest

```
--- a/Makefile.orig     2019-09-14 18:37:04.829332190 +0200
+++ a/Makefile  2019-09-14 18:40:08.090141253 +0200
@@ -348,7 +348,7 @@
                echo "$(MAKE) \
                        -C \"$(build)/$($1_dir)\" \
                        $($1_target)" ;  \
-               $(MAKE) \
+               $($1_build_environment) $(MAKE) \
                        -C "$(build)/$($1_dir)" \
                        $($1_target)  \
        ) \
```

**Comment by tlaurion** [comment]
Just saw this. Really interesting.

**Comment by tlaurion** [comment]
@jan23?

**Comment by tlaurion** [comment]
@daym There is this [PR](https://github.com/osresearch/heads/pull/714) that should resolve your issue. Please give some feeback in your use case.

**Comment by tlaurion** [comment]
#714 was merged. 

@daym:Please update if you still have issues, please tag me in.

**Comment by daym** [comment]
Thanks! It works much better now.

There are still some weird manual things we have to do:

* busybox has a build failure because it still uses CPATH although I've patched it out using make_environment.  It might be using the wrong compiler (i.e. the host compiler), but I don't know for sure
* When I build BOARD=qemu-linuxboot, coreboot builds and eventually fails because it uses i386 musl cross, which we haven't packaged yet.

**Comment by tlaurion** [comment]
@daym :
I've put your[ branch on my github](https://github.com/tlaurion/heads/tree/make-environment) for it to be picked up by CircleCI.
Error logs are out there if you click the "x":
```
make -C "/root/project/build/busybox-1.28.0" CC=/root/project/crossgcc/bin/x86_64-linux-musl-gcc -fdebug-prefix-map=/root/project=heads -gno-record-gcc-switches -D__MUSL__ -I/root/project/install/include -L/root/project/install/lib  CPP=/root/project/crossgcc/bin/x86_64-linux-musl-cpp CXXCPP=/root/project/crossgcc/bin/x86_64-linux-musl-cpp CC_FOR_BUILD= BUILD_CC= HOSTCC= AR=/root/project/crossgcc/bin/x86_64-linux-musl-ar LD=/root/project/crossgcc/bin/x86_64-linux-musl-ld STRIP=/root/project/crossgcc/bin/x86_64-linux-musl-strip NM=/root/project/crossgcc/bin/x86_64-linux-musl-nm OBJCOPY=/root/project/crossgcc/bin/x86_64-linux-musl-objcopy OBJDUMP=/root/project/crossgcc/bin/x86_64-linux-musl-objdump PKG_CONFIG_PATH=/root/project/install/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR=/root/project/install    

make[1]: Entering directory '/root/project/build/busybox-1.28.0'

rm -f .kernelrelease

echo 1.28.0 > .kernelrelease

/root/project/build/busybox-1.28.0/scripts/gen_build_files.sh /root/project/build/busybox-1.28.0 /root/project/build/busybox-1.28.0

make -f scripts/Makefile.build obj=scripts/basic

   -Wp,-MD,scripts/basic/.fixdep.d         -o scripts/basic/fixdep scripts/basic/fixdep.c  

/bin/sh: 1: -Wp,-MD,scripts/basic/.fixdep.d: not found

make[2]: *** [scripts/Makefile.host:104: scripts/basic/fixdep] Error 127

make[1]: *** [Makefile:357: scripts_basic] Error 2

make[1]: Leaving directory '/root/project/build/busybox-1.28.0'

make: *** [Makefile:387: /root/project/build/busybox-1.28.0/.build] Error 1

```

Unfortunately, I cannot merge a build system change if it breaks the current system for another use. If you can help troubleshooting to changes can make it work for both use cases.

**Comment by tlaurion** [comment]
I think this is done, where nix is used now as #1661 is merged
